<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Website\Utils\Payment\/'                 => __DIR__ . '/src/Purchase/Utils/PaymentInterface.php',
    'Website\Utils\Payment\/'                 => __DIR__ . '/src/Purchase/Utils/PaymentStripe.php',

    'Website\Module'                     => __DIR__ . '/Module.php',

    'Website\Entity\HostingPlan'                => __DIR__ . '/src/Purchase/Entity/HostingPlan.php',


    'Website\Controller\PurchaseController' => __DIR__ . '/src/Purchase/Controller/PurchaseController.php',


    'Website\Dao\HostingPlan'                => __DIR__ . '/src/Purchase/Dao/HostingPlan.php',


);

